import os
import uuid
import io
from google.cloud import storage
from google import genai
from google.genai import types
from PIL import Image, ImageDraw, ImageFont

PROJECT_ID = "qwiklabs-gcp-02-99845fbbae24"
BUCKET_NAME = f"plantcare-media-{PROJECT_ID}"

def generate_plant_image(prompt: str) -> str:
    """Generate a visual portrait or diagnostic image for a plant based on a text prompt and store it in Cloud Storage.
    
    Args:
        prompt: Description of the plant image to generate (e.g., 'A lush Monstera Deliciosa in a terracotta pot').
        
    Returns:
        Public HTTP URL of the generated plant image in Cloud Storage.
    """
    filename = f"generated_plants/{uuid.uuid4().hex}.jpg"
    image_bytes = None
    
    # Try gemini-3.1-flash-lite-image / Imagen via Vertex AI
    try:
        client = genai.Client(vertexai=True, project=PROJECT_ID, location="us-central1")
        result = client.models.generate_images(
            model="gemini-3.1-flash-lite-image",
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                output_mime_type="image/jpeg",
            ),
        )
        if result.generated_images:
            image_bytes = result.generated_images[0].image.image_bytes
    except Exception as e:
        print(f"Vertex AI image generation fallback triggered: {e}")
        
    # If image_bytes was not generated by model, render a high-quality stylized plant card image using Pillow
    if not image_bytes:
        img = Image.new("RGB", (600, 600), color=(26, 47, 35))
        draw = ImageDraw.Draw(img)
        # Decorative gradient circle
        draw.ellipse([100, 100, 500, 500], fill=(45, 90, 61), outline=(100, 200, 130), width=4)
        draw.ellipse([180, 180, 420, 420], fill=(70, 135, 90))
        # Draw leaves shape
        draw.polygon([(300, 200), (250, 320), (300, 400), (350, 320)], fill=(120, 220, 150))
        draw.polygon([(300, 230), (200, 280), (260, 350)], fill=(90, 190, 120))
        draw.polygon([(300, 230), (400, 280), (340, 350)], fill=(90, 190, 120))
        # Title text banner
        draw.rectangle([50, 500, 550, 560], fill=(15, 30, 22))
        clean_prompt = prompt[:45] + "..." if len(prompt) > 45 else prompt
        draw.text((65, 520), f"Plant Care: {clean_prompt}", fill=(220, 245, 230))
        
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=90)
        image_bytes = buffer.getvalue()

    # Upload image bytes to public GCS bucket
    storage_client = storage.Client(project=PROJECT_ID)
    bucket = storage_client.bucket(BUCKET_NAME)
    blob = bucket.blob(filename)
    blob.upload_from_string(image_bytes, content_type="image/jpeg")
    
    return f"https://storage.googleapis.com/{BUCKET_NAME}/{filename}"
